---
title: "midterm"
author: "MJ Pascual"
date: "November 12, 2017"
output: html_document
---

## Question 1

```{r setup}
library(ggplot2)
library(tidyverse)

alex <- read.csv(file="alex.csv")
year <- as.character(alex$year)
income <- as.numeric(alex$income)

c.income <- alex %>%
  filter(job == "consultant") %>%
  select(income)

c.year <- alex %>%
  filter(job == "consultant") %>%
  select(year)

ra.income <- alex %>%
  filter(job == "research assistant") %>%
  select(income, year)
  
i.income <- alex %>%
  filter(job == "instructor") %>%
  select(income, year)
  
alex.income <- ggplot(data = alex) +
  geom_area(aes(x = c.year, y = c.income, fill = job), stat="identity") + 
  labs(title="Alex's Income in Various Jobs", y="Income ($)", x = "Year") +
    theme(legend.position = "bottom") +
    theme(legend.title=element_blank()) +
    theme(plot.title = element_text(hjust = 0.5)) +
  scale_fill_manual(values = c("#43A3E6", "#EDE322", "#C1270D"))


```


## Question 2
Construct 2 side by side graphs representing the two baby names with the largest change in proportions of male to female usage and female to male usage over time. 
```{r}
library(babynames)
library(dplyr)

## testing with alex
alex.f <- 
  babynames %>%
    filter(name == "Alex", sex == "M")

alex.m <-
  babynames %>%
    filter(name == "Alex", sex == "F" )

alex <- 
  babynames %>%
    filter(name == "Alex")

play <- babynames %>% filter(name == "Alex") %>% 
  ggplot(aes(y=prop, x=year, color =sex)) + geom_line() 

ex <-ggplot(data = alex, mapping = aes(y=prop, x=year, color=sex)) + geom_line(babynames)+ facet_wrap(~name)

recked <- ggplot(babynames, aes(y=prop, x=year, color=sex)) +
  geom_line() 


babynames %>%
    filter(year) %>%
    mutate(rank = rank(-prop)) %>%
    arrange(rank) %>%
    filter(rank <= 10) %>%
    ggplot(aes(x = reorder(name, prop), y = prop)) +
    geom_bar(stat="identity", aes(fill = sex)) +
    scale_fill_manual(values = c("Pink", "Blue")) +
    xlab("Name")


```